name: Ændringsønske
description: Foreslå ny funktionalitet eller forbedring
title: "[ÆNDRING]: "
labels: ["ændringsønske"]

body:
  - type: markdown
    attributes:
      value: |
        ## Husk
        Giv en kort og præcis overskrift øverst.
        Beskriv ændringsønsket så konkret som muligt.
        ⚠️ Oplys ikke følsomme persondata i denne formular.

  - type: markdown
    attributes:
      value: |
        ### Kontaktperson

  - type: input
    id: kontaktperson_navn
    attributes:
      label: Navn
      placeholder: Indtast navn
    validations:
      required: true

  - type: input
    id: kontaktperson_mail
    attributes:
      label: Mail
      placeholder: Indtast mailadresse
    validations:
      required: true

  - type: dropdown
    id: kommune
    attributes:
      label: Kommune
      description: Vælg kommune. Hvis afsender ikke er en kommune, vælg "Ikke kommune" og udfyld feltet "Anden organisation / leverandør".
      options:
        - Albertslund
        - Allerød
        - Assens
        - Ballerup
        - Billund
        - Bornholm
        - Brøndby
        - Brønderslev
        - Dragør
        - Egedal
        - Esbjerg
        - Fanø
        - Favrskov
        - Faxe
        - Fredensborg
        - Fredericia
        - Frederiksberg
        - Frederikshavn
        - Frederikssund
        - Furesø
        - Gentofte
        - Gladsaxe
        - Glostrup
        - Greve
        - Gribskov
        - Guldborgsund
        - Haderslev
        - Halsnæs
        - Hedensted
        - Helsingør
        - Herlev
        - Herning
        - Hillerød
        - Hjørring
        - Holbæk
        - Holstebro
        - Horsens
        - Hvidovre
        - Høje-Taastrup
        - Hørsholm
        - Ikast-Brande
        - Ishøj
        - Jammerbugt
        - Kalundborg
        - Kerteminde
        - Kjellerup
        - Kolding
        - Korsør
        - Københavns
        - Køge
        - Langeland
        - Lejre
        - Lemvig
        - Lolland
        - Lyngby-Taarbæk
        - Læsø
        - Mariagerfjord
        - Middelfart
        - Morsø
        - Norddjurs
        - Nordfyns
        - Næstved
        - Odder
        - Odense
        - Odsherred
        - Randers
        - Rebild
        - Ringkøbing-Skjern
        - Ringsted
        - Roskilde
        - Rudersdal
        - Rødovre
        - Samsø
        - Silkeborg
        - Skanderborg
        - Skive
        - Slagelse
        - Solrød
        - Sorø
        - Stevns
        - Struer
        - Svendborg
        - Syddjurs
        - Sønderborg
        - Thisted
        - Tønder
        - Tårnby
        - Vallensbæk
        - Varde
        - Vejen
        - Vejle
        - Vesthimmerlands
        - Viborg
        - Vordingborg
        - Ærø
        - Aabenraa
        - Ikke kommune
    validations:
      required: true

  - type: input
    id: anden_org
    attributes:
      label: Anden organisation / leverandør
      description: Udfyld dette felt, hvis afsender ikke er en kommune (dvs. hvis du har valgt "Ikke kommune" ovenfor).
      placeholder: Navn på organisation eller leverandør
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        ### Ændringsønske

  - type: textarea
    id: forretningsbehov
    attributes:
      label: Forretningsbehov
      description: |
        ### Beskriv det bagvedliggende forretningsmæssige behov – ikke løsningen

        ### Besvar gerne:

        - Hvilket konkret problem opleves i dag?
        - Hvem er berørt (roller, medarbejdere, borgere)?
        - Hvor ofte opstår problemet?
        - Hvad er konsekvensen, hvis vi ikke ændrer noget?
        - Er der tal, data eller eksempler der understøtter behovet?

        Vær så konkret og målbar som muligt.
      placeholder: |
        Eksempel:
        Sagsbehandlere bruger i gennemsnit 15 min ekstra pr. sag pga. manuel håndtering.
        Dette påvirker ca. 120 sager pr. måned.
    validations:
      required: true

  - type: textarea
    id: beskrivelse
    attributes:
      label: Beskrivelse af ønsket ændring
      description: |
        ### Beskriv den ønskede ændring så konkret som muligt

        ### Besvar gerne:

        - Hvordan fungerer det i dag?
        - Hvad ønskes ændret eller tilføjet?
        - Hvad skal systemet kunne (gerne konkrete punkter)?
        - Hvornår vil løsningen være godkendt (acceptkriterier)?
        - Er der kendte afgrænsninger?

        Undgå at gentage forretningsbehovet – fokusér på løsningen.
      placeholder: |
        Eksempel:
        Der ønskes en automatisk validering som...
        Løsningen er godkendt når...
    validations:
      required: true

  - type: dropdown
    id: prioritet
    attributes:
      label: Oplevet prioritet
      description: |
        Vælg den prioritet du vurderer ændringsønsket har.

        ⚠ Hvis du vælger Høj eller Kritisk, skal feltet "Begrundelse" udfyldes (ellers skriv "Ikke relevant").
      options:
        - Lav
        - Mellem
        - Høj
        - Kritisk
    validations:
      required: true

  - type: textarea
    id: prioritet_begrundelse
    attributes:
      label: Begrundelse (påkrævet ved Høj eller Kritisk)
      description: |
        Skal begrundes hvis prioritet er Høj eller Kritisk.
        Ved Lav eller Mellem kan du skrive: "Ikke relevant".

        ### Beskriv gerne:

        - Hvad stopper eller risikerer at stoppe?
        - Er der lovkrav, deadlines eller økonomiske konsekvenser?
        - Er borgere eller drift direkte påvirket?
      placeholder: Beskriv hvorfor ændringen haster
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

        ### ⚠ VIGTIGT!
        **Oplys ikke følsomme persondata i denne formular.**
