name: Ændringsønske 
description: Foreslå ny funktionalitet eller forbedring
title: "Overskrift"

body:
  - type: markdown
    attributes:
      value: "### :pencil2: Husk at udfylde feltet øverst med en kort og præcis overskrift til dit ændringsønske."

  - type: markdown
    attributes:
      value: "### Kontaktperson"

  - type: input
    id: kontaktperson_navn
    attributes:
      label: Navn
      placeholder: Indtast navn
    validations:
      required: true

  - type: input
    id: kontaktperson_mail
    attributes:
      label: Mail
      placeholder: Indtast mailadresse
    validations:
      required: true

    - type: dropdown
    id: kommune
    attributes:
      label: Kommune
      options:
        - Ikke relevant
        - Albertslund
        - Allerød
        - Assens
        - Ballerup
        - Billund
        - Bornholm
        - Brøndby
        - Brønderslev
        - Dragør
        - Egedal
        - Esbjerg
        - Fanø
        - Favrskov
        - Faxe
        - Fredensborg
        - Fredericia
        - Frederiksberg
        - Frederikshavn
        - Frederikssund
        - Furesø
        - Gentofte
        - Gladsaxe
        - Glostrup
        - Greve
        - Gribskov
        - Guldborgsund
        - Haderslev
        - Halsnæs
        - Hedensted
        - Helsingør
        - Herlev
        - Herning
        - Hillerød
        - Hjørring
        - Holbæk
        - Holstebro
        - Horsens
        - Hvidovre
        - Høje-Taastrup
        - Hørsholm
        - Ikast-Brande
        - Ishøj
        - Jammerbugt
        - Kalundborg
        - Kerteminde
        - Kjellerup
        - Kolding
        - Korsør
        - Københavns
        - Køge
        - Langeland
        - Lejre
        - Lemvig
        - Lolland
        - Lyngby-Taarbæk
        - Læsø
        - Mariagerfjord
        - Middelfart
        - Morsø
        - Norddjurs
        - Nordfyns
        - Næstved
        - Odder
        - Odense
        - Odsherred
        - Randers
        - Rebild
        - Ringkøbing-Skjern
        - Ringsted
        - Roskilde
        - Rudersdal
        - Rødovre
        - Samsø
        - Silkeborg
        - Skanderborg
        - Skive
        - Slagelse
        - Solrød
        - Sorø
        - Stevns
        - Struer
        - Svendborg
        - Syddjurs
        - Sønderborg
        - Thisted
        - Tønder
        - Tårnby
        - Vallensbæk
        - Varde
        - Vejen
        - Vejle
        - Vesthimmerlands
        - Viborg
        - Vordingborg
        - Ærø
        - Aabenraa
    validations:
      required: true

  - type: textarea
    id: forretningsbehov
    attributes:
      label: Forretningsbehov
      description: Start med at beskrive hvilket forretningsbehov der ligger bagved dette ændringsønske. Gerne så konkret som muligt og med eksempel.
    validations:
      required: true

  - type: textarea
    id: beskrivelse
    attributes:
      label: Beskrivelse
      description: Beskriv dernæst hvad der ønskes ændret eller tilføjet.
    validations:
      required: true

  - type: dropdown
    id: prioritet
    attributes:
      label: Oplevet prioritet
      options:
        - Lav
        - Normal
        - Høj
        - Kritisk
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---\n### :warning: VIGTIGT!\n**Oplys ikke følsomme persondata i denne formular.**"
