name: Ændringsønske
description: Foreslå ny funktionalitet eller forbedring
title: "Overskrift"
labels: [triage, change-request]
assignees: []

body:
  - type: input
    id: kontaktperson_navn
    attributes:
      label: Kontaktperson - Navn
      placeholder: Indtast navn
    validations:
      required: true

  - type: input
    id: kontaktperson_mail
    attributes:
      label: Kontaktperson - Mail
      placeholder: Indtast mailadresse
    validations:
      required: true

  - type: input
    id: kontaktperson_kommune
    attributes:
      label: Kontaktperson - Kommune
      placeholder: Indtast kommune
    validations:
      required: true

  - type: textarea
    id: forretningsbehov
    attributes:
      label: Forretningsbehov
      description: Start med at beskrive hvilket forretningsbehov der ligger bagved dette ændringsønske. Gerne så konkret som muligt og med eksempel. VIGTIGT! Oplys ikke følsomme persondata.
    validations:
      required: true

  - type: textarea
    id: beskrivelse
    attributes:
      label: Beskrivelse
      description: Beskriv dernæst hvad der ønskes ændret eller tilføjet.
    validations:
      required: true

  - type: dropdown
    id: prioritet
    attributes:
      label: Oplevet prioritet
      options:
        - Lav
        - Normal
        - Høj
        - Kritisk
    validations:
      required: true
