name: Ændringsønske 
description: Foreslå ny funktionalitet eller forbedring
title: "Overskrift"

body:
  - type: markdown
    attributes:
      value: "### :pencil2: Husk at udfylde feltet øverst med en kort og præcis overskrift til dit ændringsønske."

  - type: markdown
    attributes:
      value: "### Kontaktperson"

  - type: input
    id: kontaktperson_navn
    attributes:
      label: Navn
      placeholder: Indtast navn
    validations:
      required: true

  - type: input
    id: kontaktperson_mail
    attributes:
      label: Mail
      placeholder: Indtast mailadresse
    validations:
      required: true

  - type: dropdown
    id: kommune
    attributes:
      label: Kommune
      options:
        - Ikke kommune
        - Albertslund
        - Allerød
        - Assens
        - Ballerup
        - Billund
        - Bornholm
        - Brøndby
        - Brønderslev
        - Dragør
        - Egedal
        - Esbjerg
        - Fanø
        - Favrskov
        - Faxe
        - Fredensborg
        - Fredericia
        - Frederiksberg
        - Frederikshavn
        - Frederikssund
        - Furesø
        - Gentofte
        - Gladsaxe
        - Glostrup
        - Greve
        - Gribskov
        - Guldborgsund
        - Haderslev
        - Halsnæs
        - Hedensted
        - Helsingør
        - Herlev
        - Herning
        - Hillerød
        - Hjørring
        - Holbæk
