name: Ændringsønske
description: Foreslå ny funktionalitet eller forbedring
title: "[FEATURE] "
labels: [triage, change-request]
assignees: []

body:
  - type: input
    id: kontaktperson
    attributes:
      label: Kontaktperson
      placeholder: Navn eller mail
    validations:
      required: true

  - type: textarea
    id: beskrivelse
    attributes:
      label: Beskrivelse
      description: Hvad ønskes ændret eller tilføjet?
    validations:
      required: true

  - type: dropdown
    id: prioritet
    attributes:
      label: Oplevet prioritet
      options:
        - Lav
        - Normal
        - Høj
        - Kritisk
    validations:
      required: true

  - type: textarea
    id: baggrund
    attributes:
      label: Baggrund
      description: Hvorfor er dette vigtigt?
