name: Ændringsønske 
description: Foreslå ny funktionalitet eller forbedring
title: "[ÆNDRING]: "
labels: ["ændringsønske"]

body:
  - type: markdown
    attributes:
      value: |
        ## Husk
        Giv en kort og præcis overskrift øverst.
        Beskriv ændringsønsket så konkret som muligt.
        ⚠️ Oplys ikke følsomme persondata i denne formular.

  # -------------------------
  # Kontaktoplysninger
  # -------------------------

  - type: markdown
    attributes:
      value: "### Kontaktperson"

  - type: input
    id: kontaktperson_navn
    attributes:
      label: Navn
      placeholder: Indtast navn
    validations:
      required: true

  - type: input
    id: kontaktperson_mail
    attributes:
      label: Mail
      placeholder: Indtast mailadresse
    validations:
      required: true

  - type: dropdown
    id: kommune
    attributes:
      label: Kommune
      options:
        - Ikke kommune
        - Albertslund
        - Allerød
        - Assens
        - Ballerup
        - Billund
        - Bornholm
        - Brøndby
        - Brønderslev
        - Dragør
        - Egedal
        - Esbjerg
        - Fanø
        - Favrskov
        - Faxe
        - Fredensborg
        - Fredericia
        - Frederiksberg
        - Frederikshavn
        - Frederikssund
        - Furesø
        - Gentofte
        - Gladsaxe
        - Glostrup
        - Greve
        - Gribskov
        - Guldborgsund
        - Haderslev
        - Halsnæs
        - Hedensted
        - Helsingør
        - Herlev
        - Herning
        - Hillerød
        - Hjørring
        - Holbæk
        - Holstebro
        - Horsens
        - Hvidovre
        - Høje-Taastrup
        - Hørsholm
        - Ikast-Brande
        - Ishøj
        - Jammerbugt
        - Kalundborg
        - Kerteminde
        - Kjellerup
        - Kolding
        - Korsør
        - Københavns
        - Køge
        - Langeland
        - Lejre
        - Lemvig
        - Lolland
        - Lyngby-Taarbæk
        - Læsø
        - Mariagerfjord
        - Middelfart
        - Morsø
        - Norddjurs
        - Nordfyns
        - Næstved
        - Odder
        - Odense
        - Odsherred
        - Randers
        - Rebild
        - Ringkøbing-Skjern
        - Ringsted
        - Roskilde
        - Rudersdal
        - Rødovre
        - Samsø
        - Silkeborg
        - Skanderborg
        - Skive
        - Slagelse
        - Solrød
        - Sorø
        - Stevns
        - Struer
        - Svendborg
        - Syddjurs
        - Sønderborg
        - Thisted
        - Tønder
        - Tårnby
        - Vallensbæk
        - Varde
        - Vejen
        - Vejle
        - Vesthimmerlands
        - Viborg
        - Vordingborg
        - Ærø
        - Aabenraa
    validations:
      required: true

  - type: input
    id: anden_org
    attributes:
      label: Anden organisation / leverandør
      description: Udfyld dette felt, hvis afsender ikke er en kommune.
      placeholder: Navn på organisation eller leverandør
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---\n### Ændringsønske"

  # -------------------------
  # Forretningsbehov
  # -------------------------

  - type: textarea
    id: forretningsbehov
    attributes:
      label: Forretningsbehov
      description: |
        ### Beskriv det bagvedliggende forretningsmæssige behov – ikke løsningen.

        Besvar gerne:
        • Hvilket konkret problem opleves i dag?
        • Hvem er berørt (roller, medarbejdere)?
        • Hvor ofte opstår problemet?
        • Hvad er konsekvensen, hvis vi ikke ændrer noget?
        • Er der tal, data eller eksempler der understøtter behovet?

        Vær så konkret og målbar som muligt.
      placeholder: |
        Eksempel:
        Sagsbehandlere bruger i gennemsnit 15 min ekstra pr. sag pga. manuel håndtering...
        Dette påvirker ca. 120 sager pr. måned...
    validations:
      required: true

 # -------------------------
  # Beskrivelse af ændring
  # -------------------------

  - type: textarea
    id: beskrivelse
    attributes:
      label: Beskrivelse af ønsket ændring
      description: |
        Beskriv hvad der konkret ønskes ændret eller tilføjet.

        Besvar gerne:
        • Hvordan fungerer det i dag?
        • Hvad ønskes ændret?
        • Hvad skal systemet kunne?
        • Hvornår vil løsningen være godkendt (acceptkriterier)?
        • Er der kendte afgrænsninger?

        Undgå at gentage forretningsbehovet – fokusér på løsningen.
      placeholder: |
        Eksempel:
        Der ønskes en automatisk validering som...
        Løsningen er godkendt når...
    validations:
      required: true

  # -------------------------
  # Prioritet
  # -------------------------

  - type: dropdown
    id: prioritet
    attributes:
      label: Oplevet prioritet
      description: |
        Vælg den prioritet du vurderer ændringsønsket har.

        ⚠ Hvis du vælger Høj eller Kritisk, skal feltet nedenfor udfyldes.
      options:
        - Lav
        - Mellem
        - Høj
        - Kritisk
    validations:
      required: true

  # -------------------------
  # Begrundelse
  # -------------------------

  - type: textarea
    id: prioritet_begrundelse
    attributes:
      label: Begrundelse (påkrævet ved Høj eller Kritisk)
      description: |
        Skal begrundes hvis prioritet er høj eller kritisk. Ved lav eller mellem kan du notere: Ikke relevant.

        Beskriv:
        • Hvad stopper eller risikerer at stoppe?
        • Er der lovkrav, deadlines eller økonomiske konsekvenser?
      placeholder: Beskriv hvorfor ændringen haster
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---\n### :warning: VIGTIGT!\n**Oplys ikke følsomme persondata i denne formular.**"
